export const jobs = [
  {
    id: "1",
    title: "Full Stack Developer",
    company: "TCS",
    description: "Build scalable web applications using React and Node.",
    type: "Full-time",
    remote: "Hybrid",
    salary: "₹6–10 LPA",
    location: "Bangalore, India",
    skills: ["React", "Node", "JavaScript", "SQL"],
  },
  {
    id: "2",
    title: "Frontend Developer",
    company: "Infosys",
    description: "Create modern UI using React and Tailwind.",
    type: "Full-time",
    remote: "On-site",
    salary: "₹4–7 LPA",
    location: "Pune, India",
    skills: ["React", "Tailwind", "JavaScript"],
  },
  {
    id: "3",
    title: "Backend Engineer",
    company: "Wipro",
    description: "Work on APIs and databases.",
    type: "Full-time",
    remote: "Remote",
    salary: "₹7–12 LPA",
    location: "Hyderabad, India",
    skills: ["Node", "Express", "MongoDB"],
  },
  {
    id: "4",
    title: "Software Engineering Intern",
    company: "Zoho",
    description: "Internship for MCA/BTech students.",
    type: "Internship",
    remote: "On-site",
    salary: "₹15k/month",
    location: "Chennai, India",
    skills: ["Java", "SQL"],
  },
  {
    id: "5",
    title: "React Developer",
    company: "Flipkart",
    description: "Frontend focused role for e-commerce.",
    type: "Contract",
    remote: "Hybrid",
    salary: "₹8–14 LPA",
    location: "Bangalore, India",
    skills: ["React", "Redux", "JavaScript"],
  },
]
